"""Trading signal data model."""

from datetime import datetime
from typing import Any

from pydantic import Field, field_validator

from bot.models.base import FrozenModel, SignalAction


class TradingSignal(FrozenModel):
    """Represents a signal generated by a trading strategy."""

    strategy_name: str
    symbol: str
    action: SignalAction
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("strategy_name", "symbol")
    @classmethod
    def non_empty_string(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Must be a non-empty string")
        return v
